Add support for loadBalancerIP
dirsigler/uptime-kuma-helm pull request #143
Opened 2023-11-15 06:53 UTC by gergaly

Add `loadBalancerIP` field to `service.yaml`

2024-01-30 09:35 UTC, lesmyrmidons commented
👍

2024-02-06 13:40 UTC, dirsigler requested changes
Also add a default value to the `values.yaml` like so:

```yaml
service:
  type: ClusterIP
  port: 3001
  nodePort:
  annotations: {}
  loadBalancerIP:
```

2024-09-27 15:15 UTC, gergaly commented
I've updated my fork with 'git commit --amend'. I think the pull request should be updated as well. Also added the option to the Readme.md

2024-12-13 11:27 UTC, dirsigler approved these changes

2026-02-16 20:52 UTC, closed without merging