Add namespace template variable
dirsigler/uptime-kuma-helm pull request #181
Opened 2024-10-22 13:38 UTC by asemarian

**Description of the change**

- Added namespaceOverride template variable to support flexible namespace configurations.
- Introduced helper function in helpers.tpl for namespace resolution.
- Updated relevant templates to utilize the new namespace logic.
- Bumped Helm chart version to 2.21.0.

**Benefits**

When using [cdk8s](https://cdk8s.io/docs/latest/), you can't scope your resources to a namespace unless the Helm chart has a template variable for that. 

**Possible drawbacks**

None that come to mind.

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md

2024-10-23 14:56 UTC, asemarian commented on charts/uptime-kuma/templates/deployment.yaml
>  kind: Deployment
test

2024-12-31 14:28 UTC, fgeck commented
Hey @dirsigler,
would it be possible to merge this PR? 
I would love to use `namespaceOverride`

2024-12-31 15:05 UTC, dirsigler commented
Hey @asemarian abd @fgeck ,
I think I can merge this once the `Chart.yaml` version bump was updated and reflects the change in `README.md` via [helm-docs](https://github.com/norwoodj/helm-docs).

Thank you for your work and patience!

2024-12-31 15:06 UTC, dirsigler requested changes
Please resolve conflict.

2025-01-05 23:13 UTC, closed without merging